all:
  children:
    production:
      hosts:
        HOST1: # Edit host (e.g. asterisk.example.com)
    develop: # NOTE pjsip config is not provisioned for developmen hosts to not break produtction endpoints
      hosts:
        DEV_HOST1: # Edit devhost (e.g. asterisk.example.com)
