---
sip_endpoints: '{{ sip_endpoints_secrets }}'

# SIP secrets
sip_id_a: '{{ vault_sipgate_id_a }}'
sip_pw_a: '{{ vault_sipgate_pw_a }}'
sip_id_b: '{{ vault_sipgate_id_b }}'
sip_pw_b: '{{ vault_sipgate_pw_b }}'

# Asterisk install
asterisk_url: 'https://downloads.asterisk.org/pub/telephony/asterisk/releases/'
asterisk_file_name: 'asterisk-18.1.0.tar.gz'
asterisk_file_sha256: 'cc12f6c228243fb736d0aa23f3ce11adf7be5c5b02ed1ca080db76605cb602df'
asterisk_install_path: '/opt/asterisk'
asterisk_fresh_install: 'no'
asterisk_install_sample_config: 'no' #only if ansible_fresh_install == 'yes'

# Asterisk config
asterisk_codecs_to_use: 'opus,alaw'

# credentials for prometheus basic auth
# and prometheus exporter to check
prometheus:
  user: prometheus
  password: '{{ vault_prometheus.password }}'